# Generated by Django 6.0.3 on 2026-03-28 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=400)),
                (
                    "schema_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Schema URI",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("license", models.CharField(blank=True, default="", max_length=200)),
                ("prefixes", models.JSONField(blank=True, default=dict)),
                ("imports", models.JSONField(blank=True, default=list)),
                (
                    "version",
                    models.CharField(blank=True, default="0.1.0", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FormSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, default="", max_length=400)),
                ("description", models.TextField(blank=True, default="")),
                ("rank", models.IntegerField(default=0)),
                ("is_root", models.BooleanField(default=False)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="builder.formtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "unique_together": {("template", "name")},
            },
        ),
        migrations.CreateModel(
            name="EnumDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enums",
                        to="builder.formtemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("template", "name")},
            },
        ),
        migrations.CreateModel(
            name="PermissibleValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("meaning", models.CharField(blank=True, default="", max_length=500)),
                ("rank", models.IntegerField(default=0)),
                (
                    "enum_def",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissible_values",
                        to="builder.enumdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, default="", max_length=400)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "range_type",
                    models.CharField(
                        choices=[
                            ("string", "Text"),
                            ("integer", "Integer"),
                            ("float", "Decimal"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("uri", "URI / Link"),
                            ("enum", "Choice (Enum)"),
                            ("object", "Object Ref"),
                        ],
                        default="string",
                        max_length=50,
                    ),
                ),
                ("range_ref", models.CharField(blank=True, default="", max_length=200)),
                ("required", models.BooleanField(default=False)),
                ("multivalued", models.BooleanField(default=False)),
                ("identifier", models.BooleanField(default=False)),
                ("key", models.BooleanField(default=False)),
                ("pattern", models.CharField(blank=True, default="", max_length=500)),
                ("minimum_value", models.IntegerField(blank=True, null=True)),
                ("maximum_value", models.IntegerField(blank=True, null=True)),
                ("minimum_cardinality", models.IntegerField(blank=True, null=True)),
                ("maximum_cardinality", models.IntegerField(blank=True, null=True)),
                ("ifabsent", models.CharField(blank=True, default="", max_length=200)),
                ("comments", models.JSONField(blank=True, default=list)),
                ("annotations", models.JSONField(blank=True, default=dict)),
                (
                    "deprecated",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("rank", models.IntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="builder.formsection",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "unique_together": {("section", "name")},
            },
        ),
    ]
